[WHISPER]
openai_whisper_api = true
faster_whisper_model_default = "large"
faster_whisper_model_local = false
faster_whisper_model_local_path = ""

[KIMI]
kimi_key = "Y"

[GPT]
openai_key = "sk-"
openai_base = "https://api.openai.com/v1"

[DEEPSEEK]
deepseek_key = "sk-"

[CHATGLM]
chatglm_key = "bd"


