[WHISPER]
openai_whisper_api = false
faster_whisper_model_default = "tiny"
faster_whisper_model_local = true
faster_whisper_model_local_path = "F:/new/model/tiny"
gpu = false
vad = false
lang = "自动识别"

[TRANSLATE]
translate_model = [ 2, 4,]
language1 = "English"
language2 = "中文"
wait_time = 0.10000000000000003
prompt_pre = "Prompt for GPT"

[SUBTITLE]
subtitle_model = "硬字幕"
font = "System"
hard_font_size = 18
soft_font_size = 60
font_color = "#ffffff"

[MORE]
min_vad = 500
beam_size = 5
whisper_prompt = "Don’t make each line too long."
temperature = 0.8
crf = 23
quality = "medium"
ffmpeg = "libx264"
log = "error"