[WHISPER]
openai_whisper_api = true
faster_whisper_model_default = "tiny"
faster_whisper_model_local = false
faster_whisper_model_local_path = "F:/new/model/tiny"
gpu = false

[MORE]
beam_size = 5
temperature = 0.8
log = "error"
