[WHISPER]
openai_whisper_api = true
faster_whisper_model_default = "tiny"
faster_whisper_model_local = false
faster_whisper_model_local_path = "D:/Project/AAVT/model/put models here（删除模型时请切换到该模型文件）"
gpu = false
vad = false
lang = "自动识别"

[TRANSLATE]
translate_model = [ 0,]
language1 = "中文"
language2 = "English"
wait_time = 0.10000000000000003
prompt_pre = "Prompt for Others"

[SUBTITLE]
subtitle_model = "硬字幕"
font = "System"
hard_font_size = 18
soft_font_size = 60
font_color = "#ffffff"
srt = "关闭"

[MORE]
min_vad = 500
beam_size = 5
whisper_prompt = "Don’t make each line too long."
temperature = 0.8
crf = 23
quality = "medium"
ffmpeg = "libx264"
log = "error"
