[WHISPER]
openai_whisper_api = true
faster_whisper_model_default = "large"
faster_whisper_model_local = false
faster_whisper_model_local_path = "F:/work/oai/Chenyme_AAVT_webui/model/tiny"
gpu = false
vad = false
lang = "ja"

[TRANSLATE]
translate_model = [ 0,]
language1 = "English"
language2 = "中文"
wait_time = 0.10000000000000003

[SUBTITLE]
subtitle_model = "硬字幕"
font = "System"
hard_font_size = 18
soft_font_size = 60
font_color = "#c31c1c"

[MORE]
min_vad = 500
beam_size = 5
whisper_prompt = "Don’t make each line too long."
temperature = 0.8
crf = 23
quality = "medium"
ffmpeg = "libx264"
log = "error"
